# Generated by Django 5.2.6 on 2025-10-02 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Expected Position')),
                ('salary_range', models.CharField(choices=[('3K-5K', '3K-5K'), ('5K-10K', '5K-10K'), ('10K-15K', '10K-15K'), ('15K-25K', '15K-25K'), ('25K-35K', '25K-35K'), ('35K+', '35K以上')], max_length=20, verbose_name='Expected Salary')),
                ('work_cities', models.JSONField(default=list, verbose_name='Preferred Cities')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20, verbose_name='Job Type')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Preferred Industry')),
                ('company_size', models.CharField(blank=True, max_length=50, verbose_name='Preferred Company Size')),
                ('other_requirements', models.TextField(blank=True, verbose_name='Other Requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Intention',
                'verbose_name_plural': 'Job Intentions',
                'db_table': 'job_intentions',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Resume Name')),
                ('file', models.FileField(upload_to='resumes/', verbose_name='Resume File')),
                ('file_size', models.IntegerField(verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(max_length=10, verbose_name='File Type')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Resume')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'db_table': 'resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
