# Generated by Django 5.2.6 on 2025-10-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Graduation Date'),
        ),
    ]
