# Generated by Django 5.2.6 on 2025-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('attachments', models.JSONField(default=list, verbose_name='Attachments')),
                ('contact_phone', models.CharField(blank=True, max_length=11, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_reply', models.TextField(blank=True, verbose_name='Admin Reply')),
                ('resolution', models.TextField(blank=True, verbose_name='Resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Feedback Category',
                'verbose_name_plural': 'Feedback Categories',
                'db_table': 'feedback_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('attachments', models.JSONField(default=list, verbose_name='Attachments')),
                ('is_admin_reply', models.BooleanField(default=False, verbose_name='Is Admin Reply')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Feedback Reply',
                'verbose_name_plural': 'Feedback Replies',
                'db_table': 'feedback_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('job', 'Job Related'), ('application', 'Application Related'), ('interview', 'Interview Related'), ('feedback', 'Feedback Related')], max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='Related Object ID')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='Related Object Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'db_table': 'system_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
