# Generated by Django 5.2.6 on 2025-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('is_success', models.BooleanField(default=True, verbose_name='Is Success')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='Failure Reason')),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'db_table': 'login_logs',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('code_type', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('reset_password', 'Reset Password'), ('change_phone', 'Change Phone')], max_length=20, verbose_name='Code Type')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Codes',
                'db_table': 'verification_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
