# Generated by Django 5.2.6 on 2025-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=20, verbose_name='Job Type')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Salary')),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('hourly', 'Hourly'), ('negotiable', 'Negotiable')], default='monthly', max_length=20, verbose_name='Salary Type')),
                ('work_city', models.CharField(max_length=100, verbose_name='Work City')),
                ('work_address', models.TextField(verbose_name='Work Address')),
                ('experience_required', models.CharField(blank=True, max_length=100, verbose_name='Experience Required')),
                ('education_required', models.CharField(blank=True, max_length=100, verbose_name='Education Required')),
                ('skills_required', models.JSONField(default=list, verbose_name='Skills Required')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('responsibilities', models.TextField(verbose_name='Responsibilities')),
                ('benefits', models.TextField(blank=True, verbose_name='Benefits')),
                ('recruitment_count', models.IntegerField(default=1, verbose_name='Recruitment Count')),
                ('application_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Application Deadline')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=20, verbose_name='Status')),
                ('view_count', models.IntegerField(default=0, verbose_name='View Count')),
                ('application_count', models.IntegerField(default=0, verbose_name='Application Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Job Favorite',
                'verbose_name_plural': 'Job Favorites',
                'db_table': 'job_favorites',
                'ordering': ['-created_at'],
            },
        ),
    ]
